---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversation-deployment
spec:
  selector:
    matchLabels:
      app: conversation # 选择这个指定标签执行
  replicas: 2 # 运行pod数量
  template:
    metadata:
      labels:
        app: conversation # 标签
    spec:
      containers:
        - name: conversation
          image: openim/conversation:v2.3.4
          # imagePullPolicy: Always
          ports:
            - containerPort: 10230
          volumeMounts:
            - name: config
              mountPath: /Open-IM-Server/config
              readOnly: true
            - name: usualConfig
              mountPath: /Open-IM-Server/config
              readOnly: true
          env:
            - name: CONFIG_NAME
              value: "/Open-IM-Server"
            - name: USUAL_CONFIG_NAME
              value: "/Open-IM-Server"
          
      volumes:
        - name: config
          configMap:
            name: openim-config
        - name: usualConfig
            configMap:
              name: openim-usualConfig
  strategy: #更新策略
    type: RollingUpdate # 滚动更新

